-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = "YES" AND 
      purchase_amount > (
        SELECT  AVG(purchase_amount)
        FROM customer
        );
        
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased AS Products,
	   ROUND(AVG(review_rating),2) AS 'Avg Review Rating'
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, 
       ROUND(AVG(purchase_amount),2) AS 'Avg Purchase Amt'
FROM customer
WHERE shipping_type IN ('Standard','Express') 
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
       COUNT(customer_id) AS 'Customer Count',
       ROUND(AVG(purchase_amount),2) AS 'Average Spent', 
       SUM(purchase_amount) AS 'Total Revenue'
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased AS Products,
       ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
SELECT item_rank, category, products, purchase_count
 FROM(
	 SELECT category,
            item_purchased AS products,
            COUNT(*) AS purchase_count,
            ROW_NUMBER() OVER (
                PARTITION BY category
                ORDER BY COUNT(*) DESC
            ) AS item_rank
     FROM customer
     GROUP BY category, item_purchased
  ) AS t
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS 'Repeat Buyers'
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, 
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;
